version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.ng-app
    command: npm run docker-start
    image: garage-door-opener/ng-app:latest
    volumes:
      - ./ng-app/src:/root/ng-app/src
    ports:
      - 4200:4200
      - 80:80
    restart: always
    container_name: ng-app
  node-service:
    build:
      context: .
      dockerfile: Dockerfile.node-service
    command: npm run start-debug
    image: garage-door-opener/node-service:latest
    volumes:
      - ./node-service/src:/root/node-service/src
    ports:
      - 8080:8080
      - 9229:9229
    restart: always
    depends_on:
      - mongo
    container_name: node-service
  python-service:
    build:
      context: .
      dockerfile: Dockerfile.python-service.prod
    command: python app.py
    image: garage-door-opener/python-service:latest
    volumes:
      - ./python-service:/root/python-service
    devices:
      - /dev/gpiomem:/dev/gpiomem
    ports:
      - 5000:5000
    restart: always
    container_name: python-service
  mongo:
    image: webhippie/mongodb:latest
    volumes:
      - mongodb:/var/lib/mongodb
    ports:
      - 27017:27017
    restart: always
    container_name: mongo
  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile.sonarqube
    image: garage-door-opener/sonarqube:latest
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - $PWD/sonar:/opt/sonarqube/data
    restart: always
    container_name: sonarqube
volumes:
  mongodb:
